const PacketMap = {
    CLIENT_TO_SERVER: {
        JOIN_GAME: "M",
        SEND_AIM: "D",
        MOVE: "9",
        RESET_MOVEMENT_DIR: "e",
        SEND_HIT: "F",
        SELECT_TO_BUILD: "z",
        SEND_UPGRADE: "H",
        AUTO_GATHER: "K",
        CREATE_CLAN: "L",
        LEAVE_CLAN: "N",
        JOIN_CLAN: "b",
        JOIN_REQUEST: "P",
        KICK_FROM_CLAN: "Q",
        STORE: "c",
        SEND_CHAT: "6",
        PING_MAP: "S",
        PING_SOCKET: "0"
    },

    SERVER_TO_CLIENT: {
        IO_INIT: "io-init",
        SET_INIT_DATA: "A",
        DISCONNECT: "B",
        SET_UP_GAME: "C",
        ADD_PLAYER: "D",
        REMOVE_PLAYER: "E",
        UPDATE_PLAYERS: "a",
        UPDATE_LEADERBOARD: "G",
        LOAD_GAME_OBJECT: "H",
        LOAD_AI: "I",
        ANIMATE_AI: "J",
        GATHER_ANIMATION: "K",
        WIGGLE_GAME_OBJECT: "L",
        SHOOT_TURRET: "M",
        UPDATE_PLAYER_VALUE: "N",
        UPDATE_HEALTH: "O",
        KILL_PLAYER: "P",
        KILL_OBJECT: "Q",
        KILL_OBJECTS: "R",
        UPDATE_ITEM_COUNTS: "S",
        UPDATE_AGE: "T",
        UPDATE_UPGRADES: "U",
        UPDATE_ITEMS: "V",
        ADD_PROJECTILE: "X",
        REMOVE_PROJECTILE: "Y",
        SERVER_RESTARTING: "Z",
        ADD_ALLIANCE: "g",
        DELETE_ALLIANCE: "1",
        ALLIANCE_NOTIFICATION: "2",
        SET_PLAYER_TEAM: "3",
        SET_ALLIANCE_PLAYERS: "4",
        UPDATE_STORE_ITEMS: "5",
        RECEIVE_CHAT: "6",
        UPDATE_MINIMAP: "7",
        SHOW_TEXT: "8",
        PING_MAP: "9",
        PING_RESPONSE: "0"
    }
} as const;

export default PacketMap;